spring.application.name=kosomo163_boot

server.port=80

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

#-------DB정보
spring.datasource.hikari.username=cns
spring.datasource.hikari.password=cns
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

#-------------mybatis
#---------DB의스네이크케이스와 자바의 카멜케이스를 똑같이 인식하게만듬
mybatis.configuration.map-underscore-to-camel-case=true
#---맵퍼 경로설정
mybatis.mapper-locations=classpath:datebase/mappers/*Mapperxml.xml