spring.application.name=kosomo163_boot

server.port=80

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

#여기의 주석  ---DB연결정보

#ip:port
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
#id
spring.datasource.hikari.username=cns
#pw
spring.datasource.hikari.password=cns
#DB JDBC 정보
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver









#----------mtbatis 설정정보
mybatis.mapper-locations=classpath:database/mappers/*Mapper.xml

#------------db의 스네이크케이스를 카멜케이스로바꿔주겠다. DTO에 저장하기위해
mybatis.configuration.map-underscore-to-camel-case=true