spring.application.name=kosomo163_boot

server.port=80

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

#-------DB정보
spring.datasource.hikari.username=cns
spring.datasource.hikari.password=cns
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

#-------------mybatis
#---------DB의스네이크케이스와 자바의 카멜케이스를 똑같이 인식하게만듬
mybatis.configuration.map-underscore-to-camel-case=true

#---이걸 작성하면 매퍼의 리졸트타입이나 파라미터타입에 들어가는 경로에 클래스명만 적어도됨
#---config파일의 타입엘리어스를 대체함. 베이스패키지명을 써놨으니 그패키지안의 클래스파일을 찾아감
#----같은 클래스명이 존재하면 에러가 발생함
mybatis.type-aliases-package=com.karina.app

#---file 관리를 위한 설정

#--- multipart 사용여부
spring.servlet.multipart.enabled=true
#---파일 하나당 최대크기 설정
spring.servlet.multipart.max-file-size=10MB
#----총 파일의 최대크기 설정
spring.servlet.multipart.max-request-size=100MB

#---파일을 저장 관리
app.upload.base=C:\\upload\\

app.upload.path=file:\\C:\\upload\\


#---폴더명
app.board.notice=notice

#--파일에 접근하기위한 가상의 URI 만들기
app.upload.url=/files/**